export const ATTRACTION_SET_INDEX   = 'ATTRACTION_SET_INDEX';
export const ATTRACTION_GET_LIST    = 'ATTRACTION_GET_LIST';
export const ATTRACTION_SET_LIST    = 'ATTRACTION_SET_LIST';
export const ATTRACTION_SET_LOADING = 'ATTRACTION_SET_LOADING';

export default {
  ATTRACTION_SET_INDEX,
  ATTRACTION_GET_LIST,
  ATTRACTION_SET_LIST,
  ATTRACTION_SET_LOADING,
};
