export const HOTEL_SET_INDEX   = 'HOTEL_SET_INDEX';
export const HOTEL_GET_LIST    = 'HOTEL_GET_LIST';
export const HOTEL_SET_LIST    = 'HOTEL_SET_LIST';
export const HOTEL_SET_LOADING = 'HOTEL_SET_LOADING';

export default {
  HOTEL_SET_INDEX,
  HOTEL_GET_LIST,
  HOTEL_SET_LIST,
  HOTEL_SET_LOADING,
};
